#cloud-config
write_files:
  - content: |
      {
        "BypassPreflightChecks": true,
        "DaemonAuthenticationType": "password",
        "DaemonAuthenticationPassword": "replicated-password",
        "ImportSettingsFrom": "/etc/settings.json",
        "LicenseFileLocation": "/etc/license.rli",
        "LogLevel": "trace",
        "ReleaseSequence": 655,
        "TlsBootstrapType": "self-signed",
        "TlsBootstrapHostname": "PUBLICIP.nip.io"
      }
    permissions: '0640'
    path: /etc/replicated.conf
  - content: |
      {
          "hostname": {
              "value": "PUBLICIP.nip.io"
          },
          "disk_path": {
              "value": "/mnt/tfe"
          },
          "enc_password": {
              "value": "CHANGEME"
          }
      }
    permissions: '0640'
    path: /etc/settings.json
runcmd:
  - sudo mkdir -p /mnt/tfe
  - yum -y update
  - yum -y install unzip
  - sudo curl -o install.sh https://install.terraform.io/ptfe/stable
  - PUBLICIP=`curl -sL http://169.254.169.254/latest/meta-data/public-ipv4`
  - sudo sed -i -e "s/PUBLICIP/$PUBLICIP/g" /etc/settings.json /etc/replicated.conf
  - pushd /var/tmp
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install --bin-dir /usr/bin --install-dir /usr/local/aws-cli --update
  - sudo aws s3 cp s3://daniela-software/license.rli /etc/license.rli 
  - sudo bash ./install.sh no-proxy private-address=$PUBLICIP public-address=$PUBLICIP
  - setenforce 0
  - getenforce
packages_update: true
packages:
  - unzip