#cloud-config
write_files:
  - content: |
      {
        "BypassPreflightChecks": true,
        "DaemonAuthenticationType": "password",
        "DaemonAuthenticationPassword": "replicated-password",
        "ImportSettingsFrom": "/etc/settings.json",
        "LicenseFileLocation": "/etc/license.rli",
        "LogLevel": "trace",
        "ReleaseSequence": 655,
        "TlsBootstrapType": "self-signed",
        "TlsBootstrapHostname": "PUBLICIP.nip.io"
      }
    permissions: '0640'
    path: /var/tmp/replicated.conf
  - content: |
      {
          "hostname": {
              "value": "PUBLICIP.nip.io"
          },
          "disk_path": {
              "value": "/mnt/tfe"
          },
          "enc_password": {
              "value": "CHANGEME"
          }
      }
    permissions: '0640'
    path: /var/tmp/settings.json
write_files:
  - content: |
      # server config file
      sudo mkdir -p /mnt/tfe
      sudo yum -y install unzip
      PUBLICIP=`curl -sL http://169.254.169.254/latest/meta-data/public-ipv4`
      echo $PUBLICIP
      sed -i -e "s/PUBLICIP/$PUBLICIP/g" /var/tmp/settings.json  /var/tmp/replicated.conf
      sudo cp /var/tmp/settings.json  /var/tmp/replicated.conf /etc
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install --bin-dir /usr/bin --install-dir /usr/local/aws-cli --update
      sudo aws s3 cp s3://daniela-software/license.rli /etc/license.rli
      sudo setenforce 1
      curl -o install.sh https://install.terraform.io/ptfe/stable
      sudo bash ./install.sh no-proxy private-address=$PUBLICIP public-address=$PUBLICIP
      sudo setenforce 0
      sudo getenforce
    permissions: '0750'
    path: /var/tmp/script.cloud_init
runcmd:
  - until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting for networking to initialise" ; sleep 3 ; done 
  - sudo bash -x /var/tmp/script.cloud_init 2>&1 | tee /var/tmp/script.log
packages_update: true
packages:
  - unzip