#cloud-config
write_files:
  - content: |
      {
        "BypassPreflightChecks": true,
        "DaemonAuthenticationType": "password",
        "DaemonAuthenticationPassword": "replicated-password",
        "ImportSettingsFrom": "/etc/settings.json",
        "LicenseFileLocation": "/etc/license.rli",
        "LogLevel": "trace",
        "ReleaseSequence": 655,
        "TlsBootstrapType": "self-signed",
        "TlsBootstrapHostname": "PUBLICIP.nip.io"
      }
    permissions: '0640'
    path: /etc/replicated.conf
  - content: |
      {
          "hostname": {
              "value": "PUBLICIP.nip.io"
          },
          "disk_path": {
              "value": "/mnt/tfe"
          },
          "enc_password": {
              "value": "CHANGEME"
          }
      }
    permissions: '0640'
    path: /etc/settings.json
runcmd:
  - until ping -c1 archive.ubuntu.com &>/dev/null; do echo "waiting for networking to initialise" ; sleep 3 ; done 
  - sudo mkdir -p /mnt/tfe
  - sudo curl -o install.sh https://install.terraform.io/ptfe/stable
  - PUBLICIP=`curl -sL http://169.254.169.254/latest/meta-data/public-ipv4`
  - sudo sed -i -e "s/PUBLICIP/$PUBLICIP/g" /etc/settings.json /etc/replicated.conf
  - sudo apt-get -y install awscli
  - sudo aws s3 cp s3://daniela-software/license.rli /etc/license.rli 
  - sudo bash ./install.sh no-proxy private-address=$PUBLICIP public-address=$PUBLICIP
packages_update: true
packages:
  - unzip